# Generated by Django 6.0.5 on 2026-05-11 00:07

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csucc_id', models.CharField(help_text='xxxxxx-xxxxxx', max_length=13, unique=True, validators=[accounts.models._validate_csucc_id])),
                ('middle_name', models.CharField(blank=True, default='', max_length=64)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff')], default='Staff', max_length=16)),
                ('security_q1', models.CharField(choices=[('mother_maiden', "What is your mother's maiden name?"), ('first_pet', 'What was the name of your first pet?'), ('elementary_school', 'What elementary school did you attend?'), ('favorite_teacher', 'Who was your favorite teacher?'), ('birth_city', 'In what city were you born?')], max_length=64)),
                ('security_a1_hash', models.CharField(max_length=256)),
                ('security_q2', models.CharField(choices=[('mother_maiden', "What is your mother's maiden name?"), ('first_pet', 'What was the name of your first pet?'), ('elementary_school', 'What elementary school did you attend?'), ('favorite_teacher', 'Who was your favorite teacher?'), ('birth_city', 'In what city were you born?')], max_length=64)),
                ('security_a2_hash', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
