# Generated by Django 6.0.5 on 2026-05-10 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=32)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Restroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('restroom_type', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('baseline', models.FloatField(default=0.5)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrooms', to='monitoring.building')),
            ],
            options={
                'ordering': ['building__name', 'restroom_type'],
                'unique_together': {('building', 'restroom_type')},
            },
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.DateTimeField(db_index=True)),
                ('predicted_odor_1h', models.FloatField()),
                ('predicted_status_1h', models.CharField(choices=[('safe', 'Safe'), ('moderate', 'Moderate'), ('poor', 'Poor'), ('hazardous', 'Hazardous'), ('critical', 'Critical')], max_length=16)),
                ('peak_hour', models.IntegerField()),
                ('worst_day', models.IntegerField(help_text='0=Sun .. 6=Sat')),
                ('hazardous_window', models.CharField(max_length=128)),
                ('narrative', models.TextField()),
                ('confidence', models.FloatField(help_text='MLR R² (0..1)')),
                ('restroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='monitoring.restroom')),
            ],
            options={
                'ordering': ['-t'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.DateTimeField(db_index=True)),
                ('mq135', models.FloatField(help_text='MQ135 — CO2 / VOC equivalent (ppm)')),
                ('mq136', models.FloatField(help_text='MQ136 — H2S / sulfur equivalent (ppm)')),
                ('mq137', models.FloatField(help_text='MQ137 — NH3 / ammonia equivalent (ppm)')),
                ('temperature', models.FloatField(help_text='°C')),
                ('humidity', models.FloatField(help_text='%')),
                ('odor', models.FloatField(help_text='composite odor index 0..100')),
                ('air_quality', models.FloatField(help_text='composite AQ score 0..100 (higher = better)')),
                ('status', models.CharField(choices=[('safe', 'Safe'), ('moderate', 'Moderate'), ('poor', 'Poor'), ('hazardous', 'Hazardous'), ('critical', 'Critical')], db_index=True, max_length=16)),
                ('restroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.restroom')),
            ],
            options={
                'ordering': ['-t'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.DateTimeField(db_index=True)),
                ('level', models.CharField(choices=[('safe', 'Safe'), ('moderate', 'Moderate'), ('poor', 'Poor'), ('hazardous', 'Hazardous'), ('critical', 'Critical')], max_length=16)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, max_length=16)),
                ('source', models.CharField(choices=[('sensor', 'Sensor escalation'), ('ai', 'AI prediction')], max_length=16)),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.aiprediction')),
                ('restroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.restroom')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.sensorreading')),
            ],
            options={
                'ordering': ['-t'],
            },
        ),
        migrations.CreateModel(
            name='CleaningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.DateTimeField(db_index=True)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('reactive', 'Reactive'), ('manual', 'Manual (admin dispatch)')], max_length=16)),
                ('duration_min', models.IntegerField(help_text='approximate cleaning duration in minutes')),
                ('odor_before', models.FloatField()),
                ('odor_after', models.FloatField()),
                ('restroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanings', to='monitoring.restroom')),
            ],
            options={
                'ordering': ['-t'],
                'indexes': [models.Index(fields=['restroom', '-t'], name='monitoring__restroo_8d9b4e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aiprediction',
            index=models.Index(fields=['restroom', '-t'], name='monitoring__restroo_47c7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['restroom', '-t'], name='monitoring__restroo_22a07b_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['restroom', '-t'], name='monitoring__restroo_54499c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['acknowledged', '-t'], name='monitoring__acknowl_3354e7_idx'),
        ),
    ]
